language: java
jdk: 
- oraclejdk8

## If we want to test against database and docker we can use these later
#services:
#- mysql
#- docker

before_install: 
## If we want to test against database we can do this
#- mysql -e 'CREATE DATABASE IF NOT EXISTS inventorydb;'
#- mysql -u root < mysql/scripts/load-data.sql
- cd inventory
 
script: 
- ./gradlew build
- ./gradlew docker
